export const SYMPTOMS: string[] = [
  'fever',
  'cough',
  'sore_throat',
  'fatigue',
  'headache',
  'nausea',
  'vomiting',
  'diarrhea',
  'shortness_of_breath',
  'chest_pain',
  'body_aches',
  'loss_of_smell',
  'runny_nose',
  'rash',
  'joint_pain',
  'wheezing',
  'increased_thirst',
  'frequent_urination',
  'blurred_vision',
  'swelling_ankles',
  'sneezing',
  'itchy_eyes',
  'abdominal_pain',
  'heartburn',
  'burning_urination',
  'dizziness',
]

export const DEFAULT_RECORD = {
  age: 35,
  sex: 'M',
  smoker: 'no',
  activity_level: 'medium',
  bmi: 25.0,
  temperature_c: 37.2,
  heart_rate: 80,
  systolic_bp: 120,
  diastolic_bp: 80,
  spo2: 98.0,
  fasting_glucose_mg_dl: 95.0,
  hba1c_pct: 5.4,
  total_cholesterol_mg_dl: 180.0,
} as const
